- name: Ensure required dependencies are present
  apt:
    name:
      - apt-transport-https
      - gnupg2
      - wget
    state: present

- name: Download Filebeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-oss-7.11.0-amd64.deb
    dest: /home/ubuntu/filebeat-oss-7.11.0-amd64.deb

- name: Install Filebeat
  apt:
    deb: /home/ubuntu/filebeat-oss-7.11.0-amd64.deb

- name: Copy Filebeat health check file
  copy:
    src: filebeat_health_check.sh
    dest: /home/ubuntu/filebeat_health_check.sh
    mode: a+x

- name: Copy Filebeat config file
  copy:
    src: ./files/filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Copy Filebeat K8s config file
  copy:
    src: ./files/filebeat_k8s_config.yml
    dest: /home/ubuntu/filebeat_k8s_config.yml
  when: tags['Name'] == 'ansible-server'

- name: Deploy filebeat on K8s
  shell: kubectl apply -f /home/ubuntu/filebeat_k8s_config.yml
  ignore_errors: true
  when: tags['Name'] == 'ansible-server'

- name: Start Filebeat
  ansible.builtin.service:
    name: filebeat
    state: started