filebeat.inputs:
  - type: log
    enabled: false
    paths:
      - "/var/log/containers/*.log"
      - "/var/lib/docker/containers/*/*.log"
      - "/var/log/auth.log"

filebeat.autodiscover:
  providers:
  - type: docker
    templates:
    - condition:
        contains:
          docker.container.image: ".*"
      config:
        - module: nginx
          access:
            input:
              type: continer
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

filebeat.modules:
  - module: system
    syslog:
      enabled: false
    auth:
      enabled: true
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.dashboards.enabled: false
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.settings:
  index.number_of_shards: 1
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
output.elasticsearch:
  hosts: ["elk.node.opsschool-lihi.consul:9200"]
  index: "filebeat-%{[agent.version]}-%{[agent.name]}-%{+yyyy.MM.dd}"
