---

- name: Print a message
  ansible.builtin.debug:
    msg: "Installing elk on {{tags['Name']}}..."

- name: changed hostname to elk
  become: true
  ansible.builtin.hostname:
    name: elk
  ignore_errors: true

- name: Upgrade all packages on server
  apt:
    upgrade: dist
    force_apt_get: yes

- name: download elsaticsearch deb file
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.10.2-amd64.deb
    dest: /home/ubuntu/elasticsearch-oss-7.10.2-amd64.deb
  when: tags['Name'] == 'elk'

- name: install elasticsearch from deb file
  apt:
    deb: /home/ubuntu/elasticsearch-oss-7.10.2-amd64.deb
  when: tags['Name'] == 'elk'

- name: change owner elastick folder on remote
  become: true
  shell: |
    sudo chown -R ubuntu /etc/elasticsearch/*
  ignore_errors: true

- name: copy elasticsearch.yml
  become: true
  copy:
    src: ./files/elasticsearch.yml
    dest: /etc/elasticsearch/
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: start elasticsearch
  systemd:
    daemon_reload: yes
    name: elasticsearch
    enabled: yes
    state: restarted

- name: download kibana
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-oss-7.10.2-amd64.deb
    dest: /tmp/kibana-oss-7.10.2-amd64.deb
  when: tags['Name'] == 'elk'

- name: install kibana
  apt:
    deb: /tmp/kibana-oss-7.10.2-amd64.deb
  when: tags['Name'] == 'elk'

- name: Configure Server hosts kibana.yml
  shell: |
    echo 'server.host: "0.0.0.0"' > /etc/kibana/kibana.yml    
  when: tags['Name'] == 'elk'

- name: start kibana
  systemd:
    daemon_reload: yes
    name: kibana
    enabled: yes
    state: restarted
  when: tags['Name'] == 'elk'

- name: copy elk consul service file
  copy:
    src: ./files/elk_consul_service.json
    dest: /etc/consul.d/
    group: consul
    owner: consul
  when: tags['Name'] == 'elk'

- name: Ensure required dependencies are present
  apt:
    name:
      - apt-transport-https
      - gnupg2
      - wget
    state: present
  when: tags['Name'] == 'elk'
